name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
      - run: npm install
      - run: npm run tailwind:css
      - run: npm run build-storybook
      - run: npm run deploy
