name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - name: Figma Action
        uses: primer/figma-action@v1.0.0-alpha.2
        with:
          args: "format=svg outputDir=./src/"
        env:
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
      - run: npm run fetch
      - run: npm run generate
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}